import { Topic } from "./types";

export const TOPIC_POOL: Topic[] = [

  // -- SYNTAX -------------------------------------------------------
  {
    id: "variables_types",
    title: "Variables & Dynamic Typing",
    description: "How Python's type system works vs statically-typed languages",
    category: "syntax",
    difficulty: 1,
    prerequisites: [],
    time_estimate_minutes: 15,
    translation_languages: ["typescript", "java", "go", "rust"],
    relevant_goals: ["any"],
    concepts: [
      "dynamic typing", "type() and isinstance()", "duck typing",
      "None vs null/undefined", "truthy/falsy differences",
    ],
    gotchas: [
      "No undefined — only None",
      "0, '', [], {}, set(), None are all falsy",
      "isinstance() preferred over type() for checks",
      "Variables are name bindings, not boxes",
    ],
    challenges: [{ id: "types_01", type: "predict" }, { id: "types_02", type: "write" }],
    zep_search_terms: ["python type system", "dynamic typing"],
  },

  {
    id: "strings_fstrings",
    title: "Strings & f-strings",
    description: "String formatting, methods, and f-string power features",
    category: "syntax",
    difficulty: 1,
    prerequisites: [],
    time_estimate_minutes: 15,
    translation_languages: ["typescript", "java"],
    relevant_goals: ["any"],
    concepts: [
      "f-strings with expressions", "str methods (split, join, strip, etc.)",
      "multiline strings", "string multiplication",
      "f-string debugging with {expr=}",
    ],
    gotchas: [
      "Strings are immutable (like JS, unlike some expectations)",
      "No string interpolation without f-prefix",
      "f'{value=}' for debug printing (3.8+)",
      "Raw strings (r\"...\") exist — they treat backslashes as literal. Useful for regex and file paths. But they CANNOT end with an odd number of backslashes. Mention this, don't make it a coding challenge.",
    ],
    challenges: [{ id: "strings_01", type: "write" }, { id: "strings_02", type: "translate" }],
    zep_search_terms: ["python f-strings", "python string formatting"],
  },

  {
    id: "comprehensions",
    title: "Comprehensions",
    description: "List, dict, set, and generator comprehensions — Python's killer feature",
    category: "syntax",
    difficulty: 2,
    prerequisites: ["variables_types"],
    time_estimate_minutes: 25,
    translation_languages: ["typescript", "java", "go"],
    relevant_goals: ["any"],
    concepts: [
      "list comprehensions", "dict comprehensions", "set comprehensions",
      "nested comprehensions", "conditional comprehensions",
      "generator expressions", "when NOT to use comprehensions",
    ],
    gotchas: [
      "Comprehensions create new scope (unlike for loops)",
      "Generator expressions use () not [] — lazy evaluation",
      "Nested comprehensions read left-to-right like nested for loops",
      "If it needs more than one line, use a regular loop",
    ],
    challenges: [
      { id: "comp_01", type: "translate" },
      { id: "comp_02", type: "write" },
      { id: "comp_03", type: "refactor" },
    ],
    zep_search_terms: ["python comprehensions", "list comprehension"],
  },

  {
    id: "unpacking_walrus",
    title: "Unpacking & the Walrus Operator",
    description: "Destructuring, starred expressions, and assignment expressions",
    category: "syntax",
    difficulty: 2,
    prerequisites: ["variables_types"],
    time_estimate_minutes: 15,
    translation_languages: ["typescript", "javascript"],
    relevant_goals: ["any"],
    concepts: [
      "tuple unpacking", "starred unpacking (*rest)",
      "walrus operator (:=)", "swap idiom (a, b = b, a)",
      "unpacking in for loops",
    ],
    gotchas: [
      "JS destructuring uses {} for objects, Python unpacking is positional",
      "Walrus operator := is assignment AND returns the value (like C's =)",
      "Can't use walrus at statement level — it's for expressions only",
    ],
    challenges: [{ id: "unpack_01", type: "translate" }, { id: "unpack_02", type: "write" }],
    zep_search_terms: ["python unpacking", "walrus operator"],
  },

  // -- DATA STRUCTURES ----------------------------------------------
  {
    id: "lists_tuples",
    title: "Lists & Tuples",
    description: "Mutable vs immutable sequences, slicing, and common patterns",
    category: "data_structures",
    difficulty: 1,
    prerequisites: [],
    time_estimate_minutes: 20,
    translation_languages: ["typescript", "java"],
    relevant_goals: ["any"],
    concepts: [
      "list methods (append, extend, insert, pop)",
      "slicing (start:stop:step)", "negative indexing",
      "tuples as immutable records", "named tuples",
      "list vs tuple — when to use which", "shallow vs deep copy",
    ],
    gotchas: [
      "list.sort() mutates in-place and returns None",
      "sorted() returns a new list",
      "Slicing creates a shallow copy",
      "a = b = [] makes both point to SAME list",
      "Tuples with one element need trailing comma: (1,) not (1)",
    ],
    challenges: [
      { id: "list_01", type: "predict" },
      { id: "list_02", type: "write" },
    ],
    zep_search_terms: ["python lists tuples", "python slicing"],
  },

  {
    id: "dicts_sets",
    title: "Dicts & Sets",
    description: "Hashmaps, sets, defaultdict, Counter — and Python-specific patterns",
    category: "data_structures",
    difficulty: 2,
    prerequisites: ["variables_types"],
    time_estimate_minutes: 25,
    translation_languages: ["typescript", "java"],
    relevant_goals: ["any"],
    concepts: [
      "dict methods (get, setdefault, items, values, keys)",
      "dict merge operator (|)", "dict comprehensions",
      "sets and set operations (union, intersection, difference)",
      "defaultdict", "Counter", "OrderedDict (and why you rarely need it now)",
      "dict insertion order guarantee (3.7+)",
    ],
    gotchas: [
      "dict.get(key, default) vs dict[key] — KeyError prevention",
      "Only hashable types can be dict keys or set members",
      "sets are unordered — don't rely on iteration order",
      "{} creates an empty dict, not an empty set — use set()",
    ],
    challenges: [
      { id: "dict_01", type: "write" },
      { id: "dict_02", type: "translate" },
    ],
    zep_search_terms: ["python dict", "python collections module"],
  },

  // -- FUNCTIONS ----------------------------------------------------
  {
    id: "functions_args",
    title: "Function Arguments",
    description: "Positional, keyword, *args, **kwargs, and argument gotchas",
    category: "functions",
    difficulty: 2,
    prerequisites: ["variables_types"],
    time_estimate_minutes: 25,
    translation_languages: ["typescript", "javascript"],
    relevant_goals: ["any"],
    concepts: [
      "positional vs keyword args", "default arguments",
      "*args and **kwargs", "keyword-only args (after *)",
      "positional-only args (before /)", "argument unpacking in calls",
    ],
    gotchas: [
      "MUTABLE DEFAULT ARGUMENTS — the #1 Python gotcha",
      "def f(lst=[]) shares the same list across calls",
      "Fix: def f(lst=None): lst = lst or []",
      "In Python, * and ** unpack IN CALLS, collect IN DEFINITIONS",
    ],
    challenges: [
      { id: "args_01", type: "predict" },
      { id: "args_02", type: "write" },
    ],
    zep_search_terms: ["python function arguments", "args kwargs"],
  },

  {
    id: "closures_decorators",
    title: "Closures & Decorators",
    description: "First-class functions, closures, nonlocal, and the decorator pattern",
    category: "functions",
    difficulty: 3,
    prerequisites: ["functions_args"],
    time_estimate_minutes: 35,
    translation_languages: ["typescript", "javascript"],
    relevant_goals: ["any"],
    concepts: [
      "functions as first-class objects", "closures and nonlocal",
      "decorator syntax (@decorator)", "decorators with arguments",
      "functools.wraps", "common stdlib decorators",
      "stacking decorators",
    ],
    gotchas: [
      "nonlocal is needed to ASSIGN to outer scope variable (not just read)",
      "JS closures 'just work' — Python needs explicit nonlocal for assignment",
      "Decorators execute at import time, not call time",
      "Without @functools.wraps, decorated function loses its name/docstring",
    ],
    challenges: [
      { id: "closure_01", type: "translate" },
      { id: "closure_02", type: "write" },
      { id: "closure_03", type: "write" },
    ],
    zep_search_terms: ["python closures", "python decorators"],
  },

  {
    id: "generators_iterators",
    title: "Generators & Iterators",
    description: "yield, generator expressions, iterator protocol, itertools",
    category: "functions",
    difficulty: 3,
    prerequisites: ["functions_args", "comprehensions"],
    time_estimate_minutes: 30,
    translation_languages: ["typescript", "javascript"],
    relevant_goals: ["any"],
    concepts: [
      "yield and generator functions", "generator expressions",
      "iterator protocol (__iter__, __next__)", "itertools basics",
      "lazy evaluation benefits", "yield from",
      "generator vs list — memory implications",
    ],
    gotchas: [
      "Generators are exhausted after one iteration",
      "JS has function* — Python uses yield in a regular def",
      "Generators can't be indexed or sliced",
      "itertools.chain, islice, groupby — know these exist",
    ],
    challenges: [
      { id: "gen_01", type: "write" },
      { id: "gen_02", type: "refactor" },
    ],
    zep_search_terms: ["python generators", "python itertools"],
  },

  // -- TYPE SYSTEM --------------------------------------------------
  {
    id: "type_hints",
    title: "Type Hints & Typing Module",
    description: "Python's optional type system — familiar territory for TS devs",
    category: "type_system",
    difficulty: 2,
    prerequisites: ["variables_types", "functions_args"],
    time_estimate_minutes: 25,
    translation_languages: ["typescript"],
    relevant_goals: ["any"],
    concepts: [
      "basic type annotations", "typing module (List, Dict, Optional, Union)",
      "modern syntax (list[int] vs List[int])", "TypeAlias",
      "Literal types", "TypeVar and generics",
      "mypy basics", "runtime behavior (hints are NOT enforced)",
    ],
    gotchas: [
      "Type hints are IGNORED at runtime — they're for tooling only",
      "This is the opposite of TypeScript where types are compile-time",
      "Optional[X] means Union[X, None], not 'parameter is optional'",
      "Use X | None (3.10+) instead of Optional[X]",
    ],
    challenges: [
      { id: "types_01", type: "translate" },
      { id: "types_02", type: "write" },
    ],
    zep_search_terms: ["python type hints", "python typing module", "mypy"],
  },

  {
    id: "protocols_abc",
    title: "Protocols & ABCs",
    description: "Structural typing (like TS interfaces) vs nominal typing in Python",
    category: "type_system",
    difficulty: 3,
    prerequisites: ["type_hints", "oop_classes"],
    time_estimate_minutes: 25,
    translation_languages: ["typescript", "go"],
    relevant_goals: ["any"],
    concepts: [
      "Protocol class (structural subtyping)", "ABC and abstractmethod",
      "Protocol vs ABC — when to use which",
      "runtime_checkable Protocol",
      "how Protocol maps to TS interfaces/Go interfaces",
    ],
    gotchas: [
      "Protocol is structural (like TS) — no explicit implements needed",
      "ABC is nominal — must explicitly inherit",
      "Protocols are the Pythonic way to do TS-style interfaces",
      "@runtime_checkable adds isinstance() support but has limitations",
    ],
    challenges: [
      { id: "protocol_01", type: "translate" },
      { id: "protocol_02", type: "write" },
    ],
    zep_search_terms: ["python protocol", "python abstract base class"],
  },

  // -- OOP ----------------------------------------------------------
  {
    id: "oop_classes",
    title: "Classes & Dataclasses",
    description: "Python OOP, dunder methods, and dataclasses for everyday use",
    category: "oop",
    difficulty: 2,
    prerequisites: ["functions_args"],
    time_estimate_minutes: 30,
    translation_languages: ["typescript", "java"],
    relevant_goals: ["any"],
    concepts: [
      "class definition and __init__", "self (explicit, not implicit like JS this)",
      "class vs instance attributes", "dataclasses",
      "@dataclass fields, defaults, frozen",
      "common dunder methods (__str__, __repr__, __eq__, __hash__)",
      "__slots__ for memory optimization",
    ],
    gotchas: [
      "self is explicit everywhere — not optional like JS this",
      "Class-level mutable attributes are SHARED across instances",
      "dataclass is preferred over manual __init__ for data containers",
      "__repr__ is for developers, __str__ is for users",
    ],
    challenges: [
      { id: "class_01", type: "translate" },
      { id: "class_02", type: "write" },
    ],
    zep_search_terms: ["python classes", "python dataclasses", "dunder methods"],
  },

  {
    id: "inheritance_composition",
    title: "Inheritance, MRO & Composition",
    description: "Multiple inheritance, MRO, mixins, and why composition usually wins",
    category: "oop",
    difficulty: 3,
    prerequisites: ["oop_classes"],
    time_estimate_minutes: 25,
    translation_languages: ["typescript", "java"],
    relevant_goals: ["any"],
    concepts: [
      "single vs multiple inheritance", "MRO (method resolution order)",
      "super() and cooperative inheritance", "mixins",
      "composition over inheritance pattern",
      "Python's approach vs Java/TS (no interfaces needed — use Protocol)",
    ],
    gotchas: [
      "Python supports multiple inheritance — most languages don't",
      "MRO follows C3 linearization — use ClassName.mro() to inspect",
      "super() in multiple inheritance can be surprising",
      "Prefer composition + Protocol over deep inheritance hierarchies",
    ],
    challenges: [
      { id: "inherit_01", type: "predict" },
      { id: "inherit_02", type: "write" },
    ],
    zep_search_terms: ["python inheritance", "python MRO", "composition vs inheritance"],
  },

  // -- ERROR HANDLING -----------------------------------------------
  {
    id: "exceptions",
    title: "Exception Handling",
    description: "try/except patterns, exception hierarchy, and custom exceptions",
    category: "error_handling",
    difficulty: 2,
    prerequisites: ["functions_args"],
    time_estimate_minutes: 20,
    translation_languages: ["typescript", "java"],
    relevant_goals: ["any"],
    concepts: [
      "try/except/else/finally", "exception hierarchy",
      "catching specific exceptions", "raising exceptions",
      "custom exception classes", "exception chaining (from)",
      "EAFP vs LBYL philosophy",
    ],
    gotchas: [
      "Python prefers EAFP (ask forgiveness) vs JS LBYL (look before you leap)",
      "Bare except: catches EVERYTHING including KeyboardInterrupt — never do this",
      "else block runs only if no exception was raised — useful for 'happy path'",
      "Exception chaining: raise NewError() from original_error",
    ],
    challenges: [
      { id: "except_01", type: "write" },
      { id: "except_02", type: "write" },
    ],
    zep_search_terms: ["python exceptions", "python error handling", "EAFP"],
  },

  {
    id: "context_managers",
    title: "Context Managers",
    description: "with statement, __enter__/__exit__, contextlib, and resource management",
    category: "error_handling",
    difficulty: 3,
    prerequisites: ["exceptions", "oop_classes"],
    time_estimate_minutes: 20,
    translation_languages: ["typescript"],
    relevant_goals: ["any"],
    concepts: [
      "with statement", "__enter__ and __exit__",
      "contextlib.contextmanager decorator",
      "multiple context managers", "async context managers",
      "common uses (files, locks, DB connections, temp resources)",
    ],
    gotchas: [
      "No equivalent in JS — using/Symbol.dispose is new and limited",
      "with guarantees cleanup even if exception occurs",
      "@contextmanager + yield is the easy way to write one",
      "__exit__ receives exception info — can suppress by returning True",
    ],
    challenges: [
      { id: "ctx_01", type: "write" },
      { id: "ctx_02", type: "write" },
    ],
    zep_search_terms: ["python context managers", "python with statement"],
  },

  // -- ASYNC --------------------------------------------------------
  {
    id: "async_fundamentals",
    title: "Async Python Fundamentals",
    description: "asyncio, async/await — and the critical differences from JS async",
    category: "async",
    difficulty: 3,
    prerequisites: ["functions_args", "exceptions"],
    time_estimate_minutes: 35,
    translation_languages: ["typescript", "javascript"],
    relevant_goals: ["any", "web_dev", "ai_ml"],
    concepts: [
      "coroutines vs regular functions", "await and async def",
      "asyncio.run() — the entry point", "asyncio.gather() for concurrency",
      "asyncio.create_task()", "event loop (implicit vs JS explicit)",
      "async for / async with", "asyncio vs threading vs multiprocessing",
    ],
    gotchas: [
      "BIGGEST DIFFERENCE: Python async is NOT like JS async",
      "JS: all I/O is async by default. Python: sync by default, async is opt-in",
      "Calling an async function returns a coroutine object, doesn't run it",
      "asyncio.run() creates the event loop — there's no top-level await (mostly)",
      "You can't mix sync and async easily — it's all or nothing (colored functions problem)",
      "asyncio.gather() is equivalent to Promise.all()",
    ],
    challenges: [
      { id: "async_01", type: "predict" },
      { id: "async_02", type: "translate" },
      { id: "async_03", type: "write" },
    ],
    zep_search_terms: ["python asyncio", "python async await", "asyncio vs javascript"],
  },

  // -- TESTING ------------------------------------------------------
  {
    id: "testing_pytest",
    title: "Testing with pytest",
    description: "pytest fundamentals — fixtures, parametrize, mocking, and TDD patterns",
    category: "testing",
    difficulty: 2,
    prerequisites: ["functions_args"],
    time_estimate_minutes: 30,
    translation_languages: ["typescript"],
    relevant_goals: ["any", "job_requirement"],
    concepts: [
      "pytest basics (test_ functions, assert)", "fixtures and conftest.py",
      "parametrize for table-driven tests", "mocking with unittest.mock",
      "pytest.raises for exception testing", "markers and skipping",
      "test organization and naming conventions",
    ],
    gotchas: [
      "pytest uses plain assert — no assertEqual/assertTrue needed",
      "Fixtures are dependency injection, not setup/teardown (though they can do both)",
      "conftest.py fixtures are auto-discovered — no imports needed",
      "Mock vs patch — patch replaces WHERE IT'S USED, not where it's defined",
    ],
    challenges: [
      { id: "test_01", type: "write" },
      { id: "test_02", type: "write" },
    ],
    zep_search_terms: ["python pytest", "python testing", "pytest fixtures"],
  },

  // -- ECOSYSTEM ----------------------------------------------------
  {
    id: "virtual_envs",
    title: "Virtual Environments & Package Management",
    description: "venv, pip, uv, pyproject.toml — Python's packaging story",
    category: "ecosystem",
    difficulty: 1,
    prerequisites: [],
    time_estimate_minutes: 20,
    translation_languages: ["typescript"],
    relevant_goals: ["any"],
    concepts: [
      "why virtual environments exist (vs node_modules)",
      "venv and activation", "pip install and requirements.txt",
      "pyproject.toml (modern standard)", "uv — the fast modern tool",
      "system Python vs project Python",
    ],
    gotchas: [
      "No node_modules equivalent — packages install globally unless you use a venv",
      "ALWAYS use a virtual environment — never pip install into system Python",
      "uv is the modern answer: fast, handles venvs + packages + Python versions",
      "requirements.txt is legacy — pyproject.toml is the standard now",
    ],
    challenges: [
      { id: "env_01", type: "explain" },
    ],
    zep_search_terms: ["python virtual environments", "python packaging", "uv python"],
  },

  // -- STDLIB -------------------------------------------------------
  {
    id: "stdlib_essentials",
    title: "Standard Library Power Tools",
    description: "pathlib, json, datetime, collections, itertools — the batteries included",
    category: "stdlib",
    difficulty: 2,
    prerequisites: ["variables_types", "dicts_sets"],
    time_estimate_minutes: 25,
    translation_languages: [],
    relevant_goals: ["any"],
    concepts: [
      "pathlib.Path (not os.path)", "json.loads/dumps",
      "datetime and timedelta", "collections (defaultdict, Counter, deque, namedtuple)",
      "itertools (chain, groupby, combinations, permutations)",
      "functools (lru_cache, partial, reduce)",
    ],
    gotchas: [
      "Use pathlib, not os.path — it's the modern way",
      "json.dumps/loads, not json.dump/load (those are for files)",
      "datetime is notoriously annoying — consider using a library for complex cases",
      "collections.Counter is magical for frequency problems",
    ],
    challenges: [
      { id: "stdlib_01", type: "write" },
      { id: "stdlib_02", type: "write" },
    ],
    zep_search_terms: ["python standard library", "python pathlib", "python collections"],
  },

  // -- PATTERNS -----------------------------------------------------
  {
    id: "pythonic_patterns",
    title: "Pythonic Patterns & Idioms",
    description: "Writing code that looks like Python, not translated Java/JS",
    category: "patterns",
    difficulty: 2,
    prerequisites: ["comprehensions", "functions_args"],
    time_estimate_minutes: 20,
    translation_languages: ["typescript", "java"],
    relevant_goals: ["any", "job_requirement"],
    concepts: [
      "enumerate() instead of range(len())", "zip() for parallel iteration",
      "any() and all()", "dictionary dispatch (replacing switch/case)",
      "match/case (3.10+, structural pattern matching)",
      "_ as throwaway variable", "the Pythonic vs un-Pythonic spectrum",
    ],
    gotchas: [
      "for i in range(len(lst)): lst[i] — this screams 'I learned another language first'",
      "match/case is NOT switch/case — it's structural pattern matching",
      "Pythonic code values readability over cleverness",
    ],
    challenges: [
      { id: "idiom_01", type: "refactor" },
      { id: "idiom_02", type: "write" },
    ],
    zep_search_terms: ["pythonic code", "python idioms", "python best practices"],
  },

  // -- AI/ML --------------------------------------------------------
  {
    id: "ai_sdk_patterns",
    title: "Working with AI APIs in Python",
    description: "OpenAI, Anthropic, and Google AI SDK patterns — streaming, tool use, structured output",
    category: "ai_ml",
    difficulty: 3,
    prerequisites: ["functions_args", "async_fundamentals", "type_hints"],
    time_estimate_minutes: 35,
    translation_languages: ["typescript"],
    relevant_goals: ["ai_ml", "ai_engineer"],
    concepts: [
      "OpenAI SDK patterns", "Anthropic SDK patterns",
      "streaming responses", "tool/function calling",
      "structured output with Pydantic", "token counting and management",
      "error handling and retries", "async SDK usage",
    ],
    gotchas: [
      "Python SDKs are first-class citizens for all AI providers",
      "Streaming in Python uses generators/async generators",
      "Pydantic is the standard for structured output parsing",
      "Type hints matter here — SDKs use them extensively",
    ],
    challenges: [
      { id: "ai_01", type: "write" },
      { id: "ai_02", type: "write" },
    ],
    zep_search_terms: ["python AI SDK", "openai python", "anthropic python sdk"],
  },

  {
    id: "data_processing",
    title: "Data Processing Patterns",
    description: "CSV, pandas basics, data pipelines — for the data-curious",
    category: "ai_ml",
    difficulty: 2,
    prerequisites: ["dicts_sets", "comprehensions"],
    time_estimate_minutes: 30,
    translation_languages: [],
    relevant_goals: ["ai_ml", "data_science", "automation"],
    concepts: [
      "csv module basics", "pandas DataFrame intro",
      "reading/writing data files", "basic data transformations",
      "groupby and aggregation", "data cleaning patterns",
    ],
    gotchas: [
      "pandas is heavy — don't use it for simple tasks",
      "DataFrames are not dicts — they have their own API",
      "polars is the faster modern alternative",
    ],
    challenges: [
      { id: "data_01", type: "write" },
      { id: "data_02", type: "write" },
    ],
    zep_search_terms: ["python pandas", "python data processing"],
  },
];
